# * under constructing

# // 0 dim
# pub struct Point;
# impl Complex for Point {
# 	fn component(&self) -> Component {
# 		Component::from(vec![1])
# 	}
# }
# impl fmt::Debug for Point {
# 	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
#         writeln!(f, "•")
#     }
# }
